# Generated by Django 4.1.4 on 2022-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annaahair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Введите ваше имя:')),
                ('review', models.TextField(verbose_name='Ваш отзыв:')),
            ],
        ),
    ]
