# Generated by Django 4.1.4 on 2022-12-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annaahair', '0002_annaahair_review_alter_annaahair_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annaahair_review',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
        migrations.RenameField(
            model_name='annaahair_review',
            old_name='review',
            new_name='review1',
        ),
        migrations.RenameField(
            model_name='annaahair_review',
            old_name='title',
            new_name='title1',
        ),
    ]
